.TH leterrier-aller 1 "November 14, 2010"
.SH NAME
leterrier\-aller- a game
.SH SYNOPSIS
.B leterrier\-aller
.SH DESCRIPTION
is a program which let's you playing ALLER !
.PP

leterrier\-aller (1)
.SH AUTHOR
This manual page and the script were written by Jean-Louis FRucot
<frucot.jeanlouis@free.fr>.
